name: earth-science-py
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - statsmodels
  - geopandas
  - rasterio
  - shapely
  - cartopy
  - folium
  - scikit-image
  - pyvista
  - pyperclip
  - notebook
  - jupyterlab
  - sqlite
  - pip
  - pip:
    - ruptures
    - pykrige
    - opencv-python
    - mplstereonet
    - streamlit
